### ISSUE TITLE
unable to find../pretrained_models/RRDB_DF2K_4X.pth

### ISSUE THREAD

**Issue by RisingEntropy** [liyuantsao/FlowSR-LP#1]
When I am running SRFlow-LP, I get an error like this:
```bash
FileNotFoundError: [Errno 2] No such file or directory: '../pretrained_models/RRDB_DF2K_4X.pth'
```
However, I can't find where to download the RRDB_DF2K_4X.pth

**Comment by liyuantsao** [comment]
Thank you for your question!

When you run the following lines in `setup.sh`, checkpoints provided by SRFlow will be downloaded, including the required `RRDB_DF2K_4X.pth` and `SRFlow_DF2K_4X`:
```
wget --continue http://data.vision.ee.ethz.ch/alugmayr/SRFlow/pretrained_models.zip
unzip pretrained_models.zip
rm pretrained_models.zip
```

**Comment by RisingEntropy** [comment]
Thank you for your help very much!

**Comment by Oguzhanercan** [comment]
Link is broken, 
HTTP request sent, awaiting response... 404 Not Found
2024-07-01 15:00:23 ERROR 404: Not Found.

can you share parameters with google drive? Thanks

**Comment by oylz** [comment]
> Link is broken, HTTP request sent, awaiting response... 404 Not Found 2024-07-01 15:00:23 ERROR 404: Not Found.
> 
> can you share parameters with google drive? Thanks

+1, can you share?thanks @liyuantsao

**Comment by liyuantsao** [comment]
Hi @Oguzhanercan and @oylz,

Sorry for the late reply! Here's the checkpoints:

[SRFlow_DF2K_4X.pth](https://drive.google.com/file/d/1IGiAudmkQibuUMhADDEC9NEfECsEhoSJ/view?usp=sharing)
[RRDB_DF2K_4X.pth](https://drive.google.com/file/d/11yA6cIHpagTr9q0bL3bY9Qif4JSqupIf/view?usp=sharing)

Copyright: [SRFlow](https://github.com/andreas128/SRFlow)

**Comment by oylz** [comment]
> Hi @Oguzhanercan and @oylz,
> 
> Sorry for the late reply! Here's the checkpoints:
> 
> [SRFlow_DF2K_4X.pth](https://drive.google.com/file/d/1IGiAudmkQibuUMhADDEC9NEfECsEhoSJ/view?usp=sharing) [RRDB_DF2K_4X.pth](https://drive.google.com/file/d/11yA6cIHpagTr9q0bL3bY9Qif4JSqupIf/view?usp=sharing)
> 
> Copyright: [SRFlow](https://github.com/andreas128/SRFlow)

**thank you very much!**

**Comment by Oguzhanercan** [comment]
> Hi @Oguzhanercan and @oylz,
> 
> Sorry for the late reply! Here's the checkpoints:
> 
> [SRFlow_DF2K_4X.pth](https://drive.google.com/file/d/1IGiAudmkQibuUMhADDEC9NEfECsEhoSJ/view?usp=sharing) [RRDB_DF2K_4X.pth](https://drive.google.com/file/d/11yA6cIHpagTr9q0bL3bY9Qif4JSqupIf/view?usp=sharing)
> 
> Copyright: [SRFlow](https://github.com/andreas128/SRFlow)

thanks a lot

**Comment by oylz** [comment]
> > Hi @Oguzhanercan and @oylz,
> > Sorry for the late reply! Here's the checkpoints:
> > [SRFlow_DF2K_4X.pth](https://drive.google.com/file/d/1IGiAudmkQibuUMhADDEC9NEfECsEhoSJ/view?usp=sharing) [RRDB_DF2K_4X.pth](https://drive.google.com/file/d/11yA6cIHpagTr9q0bL3bY9Qif4JSqupIf/view?usp=sharing)
> > Copyright: [SRFlow](https://github.com/andreas128/SRFlow)
> 
> thanks a lot

**thank you**
